### ISSUE TITLE
Warn

### ISSUE THREAD

**Issue by monstertrakk** [hiephtdev/allora-worker#3]
> {"level":"error","error":"failed to make request to http://source-01:8001/truth/BTCUSD/639899: Get \"http://source-01:8001/truth/BTCUSD/639899\": dial tcp: lookup source-01 on 127.0.0.11:53: no such host","topicId":3,"time":1723736781,"message":"Error building and committing reputer payload for topic"}
> {"level":"debug","topicId":9,"time":1723736781,"message":"Checking for latest open worker nonce"}
> {"level":"debug","topicId":3,"time":1723736782,"message":"Checking for latest open worker nonce"}
> {"level":"error","error":"error code: '10' msg: 'failed to execute message; message index: 0: address is not registered in this topic'","msg":"Add reputer stake","time":1723736782,"message":"Failed, retrying... (Retry 1/1)"}
> {"level":"debug","topicId":6,"time":1723736782,"message":"Checking for latest open worker nonce"}
> {"level":"debug","topicId":4,"time":1723736783,"message":"Checking for latest open worker nonce"}
> {"level":"debug","topicId":6,"time":1723736783,"message":"Checking for latest open reputer nonce"}
> {"level":"debug","topicId":6,"time":1723736783,"message":"Building and committing reputer payload for topic"}
> {"level":"info","req":"{\"topic_id\":6,\"block_height_last_inference\":622733,\"block_height_last_reward\":605453}","time":1723736783,"message":"Getting QueryNetworkInferencesAtBlockRequest from chain"}
> {"level":"debug","topicId":8,"time":1723736784,"message":"Checking for latest open worker nonce"}
> {"level":"debug","url":"http://source-03:8003/truth/SOLUSD/622733","time":1723736784,"message":"Source of truth"}
> {"level":"error","error":"failed to make request to http://source-03:8003/truth/SOLUSD/622733: Get \"http://source-03:8003/truth/SOLUSD/622733\": dial tcp: lookup source-03 on 127.0.0.11:53: no such host","topicId":6,"time":1723736784,"message":"Failed to get source truth from reputer"}
> {"level":"error","error":"failed to make request to http://source-03:8003/truth/SOLUSD/622733: Get \"http://source-03:8003/truth/SOLUSD/622733\": dial tcp: lookup source-03 on 127.0.0.11:53: no such host","topicId":6,"time":1723736784,"message":"Error building and committing reputer payload for topic"}
>

**Comment by 0xsyncroot** [comment]
check logs in container source=01, source-02,source-03, and upload images logs in current issue, please
