### ISSUE TITLE
how to change rpc

### ISSUE THREAD

**Issue by Gifty7** [hiephtdev/allora-worker#4]
how to change rpc

**Comment by 0xsyncroot** [comment]
![Screenshot 2024-08-18 143536](https://github.com/user-attachments/assets/87e3c777-0d6b-470e-993f-58baf4f93ca2)

In the node directory, modify the rpc in the `config.json` file to the desired RPC.
Then, run the command 

```bash
init.config.sh --i
```

Finally, run the command to start the node again

```bash
docker compose up -d
```

or 

```bash
docker restart node
```

 to restart the current worker correctly
