### ISSUE TITLE
VPS stuck after installing your node

### ISSUE THREAD

**Issue by shaikhbazil** [hiephtdev/allora-worker#5]
Hello, i am using 2 core and 2 gb RAM VPS, but once i installed your node it got stuck to a point where i have to reinstall the OS.

May i ask what VPS specs are you using or do i need to upgrade my VPS and are you still receiving points as of now

**Comment by 0xsyncroot** [comment]
## The version you are running might include the node, which could result in higher RAM usage than usual.

### If you check the running version and it includes the node, the minimum RAM required is 4GB.
To resolve this issue, please fetch the latest code from the current repository, then remove all the old running containers by following these steps:
- Go to the node directory and type command for remove old container

```bash
docker compose down.
```

- Fetch the new code and then set it up again from scratch, skipping step 2.
Type the command 

```bash
docker compose up -d --build
```

If you still encounter the issue, you can edit the `docker-compose.yaml` and `config.json` files to skip the topic step.
Thanks.
